/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Collection = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'collection' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'price' : IDL.Float64,
  'images' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'init' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Collection = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'collection' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'price' : IDL.Float64,
    'images' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'init' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };